### ISSUE TITLE
Splunk Alert MS Teams workflows compatibility

### ISSUE THREAD

**Issue by Aezox13** [MattLParker/Splunk-alert_microsoftteams#11]
Hello, 

Microsoft has recently announced that O365 Connectors (webhooks) are deprecated and will be removed from Teams October 1st 2024.
[https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams](url)

Is there any plans to update the Splunk add-on to make it compatible with MS Teams workflow feature ?

**Comment by MattLParker** [comment]
I will have to try and test it, Some of my other things just work on the new workflow connector, It would be awesome if you could test and report the results back.

**Comment by Aezox13** [comment]
Thanks for your feedback, I am going to give it a try and provide feedback on my side

**Comment by Aezox13** [comment]
> I will have to try and test it, Some of my other things just work on the new workflow connector, It would be awesome if you could test and report the results back.

Performed some testings and unfortunately it is not working as expected. 

Splunk is able to connect to MS Teams to trigger the Workflow but the Workflow fails. 
Looks like the addon doesn't send the adaptive card in a format known by Workflows 

![image](https://github.com/user-attachments/assets/d926b481-d3ca-4f3e-b47b-11c33a89a82f)

**Comment by MattLParker** [comment]
Can you give the build here a try: (Note the new config toggle for workflows.) If it works can you also send me a screenshot of the new settings page, I don't have a splunk box to test with right now.
https://github.com/MattLParker/Splunk-alert_microsoftteams/actions/runs/10388084784/artifacts/1811361842

**Comment by MattLParker** [comment]
I stood up a test box. I'll try to get a new build out in the next day or so.

**Comment by MattLParker** [comment]
Resolved in: https://github.com/MattLParker/Splunk-alert_microsoftteams/pull/12

Feel free to grab release manually, Will be uploading to Splunkbase shortly. Cheers.

**Comment by MattLParker** [comment]
https://splunkbase.splunk.com/app/5335
Finally approved on their end. :)
