### ISSUE TITLE
Not an Issue - Just A Little Education Please

### ISSUE THREAD

**Issue by eljefe-3** [MattLParker/Splunk-alert_microsoftteams#3]
I have installed the APP you created and attempting to configure an alert within Splunk to my webhook.  I not sure if I understand the Action and Button URL .  

Are they required?

If so do I create this actions within O365?

Thank you for your in advance for your help.

**Comment by MattLParker** [comment]
They are not required. actionURL is a table column that would have a web link in it such as to a remote dashboard not in Splunk that would be relevant to the event. The action url button name is simply the teams friendly display for such a button... Both are optional if blank the only button will be to the Splunk search. Whereas Action URL = "Dashboard" in the table. and the Button name could be "View in AppDashboard"

|User|Action|Dashboard|
|----|----|----|
|baduser|clicked link|http://appdashboardnotareallink.com/userevent|
