### ISSUE TITLE
Splunk Cloud Vetting

### ISSUE THREAD

**Issue by EatMoreChicken** [MattLParker/Splunk-alert_microsoftteams#5]
Hi! 👋🏽

I ran the app through Splunk Cloud vetting and it seems to have passed with no blockers. The only issues it pointed out were some warnings that doesn't prevent it from being installed on Splunk Cloud.

I'm not sure what the process looks like, but could you get the app to be Splunk Cloud vetted on Splunk Base?

Thank you! 😊

Here are the warning if you need:
![image](https://github.com/MattLParker/Splunk-alert_microsoftteams/assets/31674363/b5c76a5e-710e-4038-aa09-8f9a550ad258)

**Comment by MattLParker** [comment]
I haven't had a good chance to follow up on all the changes, I just submitted a version that is pending now, Hopefully it works.

**Comment by MattLParker** [comment]
This has been approved in Splunk cloud, I apologize on the late ping on this, it is a bit of a side project now that I don't actively use myself. :)

**Comment by EatMoreChicken** [comment]
Thanks Matt!
